/**
 * 525 Trivia Categories for Question Generation
 * Each category is mapped to a number (1-525) for randomization
 */
export const TRIVIA_CATEGORIES = [
  // Current Categories (1-23)
  "History",
  "Science",
  "Literature",
  "Film & TV",
  "Sports",
  "Geography",
  "Arts",
  "Technology",
  "General Knowledge",
  "Music",
  "Food & Drink",
  "Nature & Animals",
  "Greek Mythology",
  "Roman Mythology",
  "Norse Mythology",
  "Egyptian Mythology",
  "Space & Astronomy",
  "Video Games",
  "Politics & Government",
  "Business & Economics",
  "Health & Medicine",
  "Architecture",
  "Fashion",

  // Pop Culture & Entertainment (24-31)
  "Anime & Manga",
  "Comic Books & Graphic Novels",
  "Broadway & Theater",
  "Podcasts & Radio",
  "Memes & Internet Culture",
  "Reality TV",
  "Stand-Up Comedy",
  "Award Shows & Ceremonies",

  // Academic & Intellectual (32-41)
  "Philosophy",
  "Psychology",
  "Linguistics & Languages",
  "Anthropology",
  "Sociology",
  "Mathematics",
  "Chemistry",
  "Physics",
  "Biology",
  "Astronomy",

  // Regional & Cultural (42-49)
  "Asian History & Culture",
  "European History & Culture",
  "Latin American History & Culture",
  "Middle Eastern History & Culture",
  "African History & Culture",
  "Ancient Civilizations",
  "Indigenous Cultures",
  "World Religions",

  // Historical Eras (50-61)
  "Ancient Rome",
  "Ancient Greece",
  "Medieval Times",
  "Renaissance Era",
  "Age of Exploration",
  "Industrial Revolution",
  "World Wars",
  "Cold War Era",
  "1960s-1970s Culture",
  "1980s Nostalgia",
  "1990s Nostalgia",
  "2000s Pop Culture",

  // Professional & Specialized (62-69)
  "Law & Legal Systems",
  "Military & Warfare",
  "Aviation & Aerospace",
  "Maritime & Naval History",
  "Engineering & Innovation",
  "Medicine & Healthcare",
  "Education & Academia",
  "Journalism & Media",

  // Hobbies & Lifestyle (70-79)
  "Cooking & Culinary Arts",
  "Wine & Spirits",
  "Coffee & Tea",
  "Fitness & Exercise",
  "Yoga & Meditation",
  "Board Games & Tabletop",
  "Card Games & Poker",
  "Puzzles & Brain Teasers",
  "Photography",
  "Gardening & Horticulture",

  // Sports Specific (80-89)
  "Soccer/Football",
  "Basketball",
  "Baseball",
  "American Football",
  "Tennis",
  "Golf",
  "Olympic Sports",
  "Extreme Sports",
  "Combat Sports (MMA, Boxing)",
  "Motorsports & Racing",

  // Arts Specific (90-98)
  "Classical Music",
  "Jazz & Blues",
  "Rock & Roll History",
  "Hip Hop & Rap",
  "Country Music",
  "Electronic & Dance Music",
  "Painting & Visual Arts",
  "Sculpture",
  "Street Art & Graffiti",

  // Science & Nature Specific (99-107)
  "Marine Biology & Oceanography",
  "Dinosaurs & Paleontology",
  "Insects & Entomology",
  "Birds & Ornithology",
  "Ecology & Environment",
  "Climate & Weather",
  "Volcanoes & Earthquakes",
  "Genetics & DNA",
  "Neuroscience",

  // Technology Specific (108-115)
  "Social Media & Platforms",
  "Cryptocurrency & Blockchain",
  "Artificial Intelligence",
  "Cybersecurity",
  "Programming & Coding",
  "Smartphones & Mobile Tech",
  "Gaming Hardware & Consoles",
  "Internet History",

  // Quirky & Fun (116-125)
  "Urban Legends & Folklore",
  "Conspiracy Theories (debunked)",
  "Guinness World Records",
  "Famous Disasters & Accidents",
  "Unsolved Mysteries",
  "Famous Trials & Court Cases",
  "Hoaxes & Pranks",
  "Inventions & Patents",
  "Superstitions & Traditions",
  "Oddities & Strange Facts",

  // Literature Specific (126-133)
  "Poetry",
  "Science Fiction",
  "Fantasy Literature",
  "Mystery & Detective Fiction",
  "Horror & Gothic Literature",
  "Romance Novels",
  "Children's Literature",
  "Shakespeare",

  // Geography Specific (134-141)
  "World Capitals",
  "Mountains & Peaks",
  "Rivers & Lakes",
  "Deserts & Biomes",
  "Islands & Archipelagos",
  "US Geography",
  "European Geography",
  "Flags & Symbols",

  // Food & Drink Specific (142-148)
  "Baking & Pastries",
  "International Cuisine",
  "Fast Food & Chains",
  "Vegetarian & Vegan",
  "Cocktails & Mixology",
  "Craft Beer & Brewing",
  "Candy & Sweets",

  // Miscellaneous (149-162)
  "Toys & Collectibles",
  "Brands & Logos",
  "Advertising & Marketing",
  "Holidays & Celebrations",
  "Weddings & Traditions",
  "Etiquette & Manners",
  "Crime & Criminology",
  "Espionage & Spies",
  "Pirates & Privateers",
  "Royalty & Nobility",
  "Haunted Places & Ghost Stories",
  "Amusement Parks & Theme Parks",
  "Magic & Illusions",
  "Cartoons & Animation",

  // Web3 & Crypto Specific (163-168)
  "Bitcoin History & Technology",
  "Ethereum & Smart Contracts",
  "DeFi Protocols & Mechanisms",
  "NFT Art & Collections",
  "Blockchain Consensus Mechanisms",
  "Crypto Regulations & Legal Cases",

  // Specific Literary Works (169-198)
  "Lord of the Rings",
  "Harry Potter Series",
  "Game of Thrones / A Song of Ice and Fire",
  "The Chronicles of Narnia",
  "Dune",
  "Foundation Series",
  "Sherlock Holmes Stories",
  "Agatha Christie Novels",
  "Stephen King Works",
  "H.P. Lovecraft & Cthulhu Mythos",
  "Jane Austen Novels",
  "Charles Dickens Works",
  "Ernest Hemingway",
  "F. Scott Fitzgerald",
  "Gabriel García Márquez",
  "1984 & George Orwell",
  "Brave New World",
  "To Kill a Mockingbird",
  "The Great Gatsby",
  "Moby Dick",
  "Pride and Prejudice",
  "War and Peace",
  "The Odyssey & Homer",
  "The Divine Comedy",
  "Don Quixote",
  "Crime and Punishment",
  "The Catcher in the Rye",
  "One Hundred Years of Solitude",
  "The Canterbury Tales",
  "Beowulf",

  // Specific Historical Events (199-213)
  "The Apollo Moon Missions",
  "Fall of the Berlin Wall",
  "The French Revolution",
  "American Civil War Battles",
  "Manhattan Project",
  "Space Shuttle Disasters",
  "Great Depression Economics",
  "Cuban Missile Crisis",
  "Watergate Scandal",
  "9/11 Attacks & Aftermath",
  "COVID-19 Pandemic",
  "Arab Spring",
  "Brexit",
  "Chernobyl Disaster",
  "Mount Vesuvius & Pompeii",

  // Specific Science Topics (214-233)
  "Quantum Mechanics",
  "String Theory",
  "Black Holes & Event Horizons",
  "CRISPR & Gene Editing",
  "Stem Cell Research",
  "Nanotechnology",
  "Particle Accelerators & CERN",
  "Dark Matter & Dark Energy",
  "Antimatter",
  "Nuclear Fusion",
  "Superconductivity",
  "Thermodynamics",
  "Relativity Theory",
  "Photosynthesis & Plant Biology",
  "Human Immune System",
  "Virology & Pandemics",
  "Antibiotic Resistance",
  "Vaccines & Immunology",
  "Human Genome Project",
  "Epigenetics",

  // Niche Hobbies & Activities (234-253)
  "Origami",
  "Calligraphy",
  "Bonsai Trees",
  "Model Trains",
  "Scale Model Building",
  "Stamp Collecting",
  "Coin Collecting",
  "Amateur Radio (Ham Radio)",
  "Birdwatching",
  "Rock Climbing",
  "Scuba Diving",
  "Skydiving",
  "Spelunking & Caving",
  "Metal Detecting",
  "Kite Flying",
  "Falconry",
  "Beekeeping",
  "Mushroom Foraging",
  "Geocaching",
  "Astronomy & Stargazing",

  // Specific Film & TV Franchises (254-275)
  "Star Wars Universe",
  "Star Trek Universe",
  "Marvel Cinematic Universe",
  "DC Comics Adaptations",
  "James Bond Films",
  "Indiana Jones Series",
  "Jurassic Park Franchise",
  "The Matrix Trilogy",
  "Breaking Bad",
  "The Sopranos",
  "The Wire",
  "Friends",
  "Seinfeld",
  "The Office",
  "Doctor Who",
  "Stranger Things",
  "The Simpsons",
  "South Park",
  "Rick and Morty",
  "Black Mirror",
  "Arrested Development",
  "Parks and Recreation",

  // Musical Artists & Bands (276-295)
  "The Beatles",
  "The Rolling Stones",
  "Led Zeppelin",
  "Pink Floyd",
  "Queen",
  "David Bowie",
  "Bob Dylan",
  "Michael Jackson",
  "Madonna",
  "Prince",
  "Nirvana",
  "Radiohead",
  "Kanye West",
  "Beyoncé",
  "Taylor Swift",
  "The Grateful Dead",
  "Wu-Tang Clan",
  "Daft Punk",
  "Metallica",
  "AC/DC",

  // Video Game Franchises (296-315)
  "Super Mario Series",
  "The Legend of Zelda",
  "Pokémon Games",
  "Final Fantasy Series",
  "The Elder Scrolls",
  "Fallout Series",
  "Grand Theft Auto",
  "Call of Duty",
  "Halo Series",
  "Dark Souls & Souls-like Games",
  "Minecraft",
  "Fortnite",
  "League of Legends",
  "Dota 2",
  "Counter-Strike",
  "World of Warcraft",
  "The Witcher Games",
  "Red Dead Redemption",
  "Metal Gear Solid",
  "Resident Evil",

  // Specific Artists & Movements (316-330)
  "Leonardo da Vinci",
  "Vincent van Gogh",
  "Pablo Picasso",
  "Salvador Dalí",
  "Andy Warhol",
  "Banksy",
  "Michelangelo",
  "Rembrandt",
  "Claude Monet",
  "Impressionism",
  "Surrealism",
  "Cubism",
  "Renaissance Art",
  "Baroque Art",
  "Art Deco",

  // Specific Sports Figures (331-345)
  "Michael Jordan",
  "Muhammad Ali",
  "Babe Ruth",
  "Tom Brady",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Serena Williams",
  "Tiger Woods",
  "Usain Bolt",
  "Michael Phelps",
  "Wayne Gretzky",
  "Pelé",
  "Diego Maradona",
  "LeBron James",
  "Kobe Bryant",

  // Regional Cuisines (346-360)
  "Japanese Cuisine & Sushi",
  "Italian Regional Dishes",
  "French Haute Cuisine",
  "Thai Street Food",
  "Indian Curries & Spices",
  "Mexican Authentic Cuisine",
  "Chinese Regional Cooking",
  "Korean BBQ & Banchan",
  "Vietnamese Pho & Street Food",
  "Spanish Tapas & Paella",
  "Greek Mediterranean Food",
  "Turkish Kebabs & Mezes",
  "Lebanese Middle Eastern",
  "Ethiopian Cuisine",
  "Peruvian Ceviche & Dishes",

  // Architectural Styles & Landmarks (361-375)
  "Gothic Architecture",
  "Brutalist Architecture",
  "Art Nouveau",
  "Bauhaus Design",
  "Frank Lloyd Wright",
  "The Eiffel Tower",
  "The Taj Mahal",
  "The Great Wall of China",
  "Machu Picchu",
  "The Colosseum",
  "Petra Jordan",
  "Angkor Wat",
  "Sagrada Familia",
  "Burj Khalifa",
  "Sydney Opera House",

  // Specific Scientific Figures (376-390)
  "Albert Einstein",
  "Isaac Newton",
  "Marie Curie",
  "Charles Darwin",
  "Nikola Tesla",
  "Stephen Hawking",
  "Richard Feynman",
  "Carl Sagan",
  "Alan Turing",
  "Ada Lovelace",
  "Galileo Galilei",
  "Johannes Kepler",
  "Rosalind Franklin",
  "Jane Goodall",
  "Neil deGrasse Tyson",

  // Fashion Designers & Brands (391-405)
  "Coco Chanel",
  "Christian Dior",
  "Yves Saint Laurent",
  "Giorgio Armani",
  "Versace",
  "Gucci",
  "Louis Vuitton",
  "Prada",
  "Hermès",
  "Ralph Lauren",
  "Calvin Klein",
  "Alexander McQueen",
  "Vivienne Westwood",
  "Balenciaga",
  "Off-White & Virgil Abloh",

  // Mythical Creatures & Folklore (406-420)
  "Dragons in World Mythology",
  "Vampires & Vampire Lore",
  "Werewolves & Lycanthropy",
  "Zombies in Pop Culture",
  "Fairies & Fae Folk",
  "Mermaids & Sea Mythology",
  "Phoenix & Rebirth Myths",
  "Unicorns in Mythology",
  "Japanese Yokai",
  "Celtic Mythology",
  "Slavic Folklore",
  "Native American Legends",
  "African Folklore",
  "Aztec Mythology",
  "Mayan Mythology",

  // Specific Tech Companies & Products (421-435)
  "Apple Inc. History",
  "Microsoft & Windows",
  "Google & Search Algorithms",
  "Amazon & Jeff Bezos",
  "Tesla & Electric Vehicles",
  "SpaceX & Mars Missions",
  "Meta (Facebook) History",
  "Twitter/X Platform",
  "Netflix & Streaming Wars",
  "iPhone Evolution",
  "PlayStation History",
  "Xbox Gaming",
  "Nintendo Consoles",
  "IBM & Computing History",
  "Intel & Microprocessors",

  // Psychological Phenomena (436-450)
  "Cognitive Biases",
  "Optical Illusions",
  "Memory & Mnemonics",
  "Dreams & Dream Analysis",
  "Phobias & Fears",
  "Personality Types & MBTI",
  "Pavlovian Conditioning",
  "Maslow's Hierarchy of Needs",
  "The Placebo Effect",
  "Confirmation Bias",
  "Dunning-Kruger Effect",
  "Stockholm Syndrome",
  "Impostor Syndrome",
  "Cognitive Dissonance",
  "Game Theory & Prisoner's Dilemma",

  // Extreme Geography (451-465)
  "Mount Everest Expeditions",
  "Mariana Trench",
  "Amazon Rainforest",
  "Sahara Desert",
  "Antarctica Exploration",
  "The Arctic & North Pole",
  "Death Valley",
  "The Dead Sea",
  "Grand Canyon",
  "Great Barrier Reef",
  "Galápagos Islands",
  "Iceland's Volcanic Landscape",
  "Norwegian Fjords",
  "New Zealand Geography",
  "Patagonia Region",

  // Musical Instruments (466-480)
  "Piano & Keyboard History",
  "Guitar Types & Techniques",
  "Violin & String Instruments",
  "Drums & Percussion",
  "Saxophone & Jazz",
  "Synthesizers & Electronic Music",
  "Traditional Asian Instruments",
  "African Drums & Percussion",
  "Bagpipes",
  "Theremin",
  "Pipe Organ",
  "Harmonica",
  "Accordion",
  "Ukulele",
  "Banjo & Bluegrass",

  // Philosophical Schools & Concepts (481-495)
  "Stoicism",
  "Existentialism",
  "Nihilism",
  "Buddhism Philosophy",
  "Taoism & The Tao Te Ching",
  "Confucianism",
  "Epicureanism",
  "Utilitarianism",
  "Kantian Ethics",
  "Nietzsche's Philosophy",
  "Socratic Method",
  "Plato's Republic",
  "Aristotelian Logic",
  "Descartes & Rationalism",
  "Empiricism & John Locke",

  // Military History (496-525)
  "Ancient Roman Military",
  "Napoleonic Wars",
  "American Revolutionary War",
  "Vietnam War",
  "Korean War",
  "Gulf War & Desert Storm",
  "D-Day & Normandy Invasion",
  "Battle of Stalingrad",
  "Battle of Midway",
  "Siege of Constantinople",
  "Hundred Years War",
  "Samurai & Feudal Japan Warfare",
  "Medieval Siege Warfare",
  "U.S. Civil War Tactics",
  "Special Forces & Elite Units",
  "World War I Battles & Trenches",
  "Pacific Theater WWII",
  "European Theater WWII",
  "Alexander the Great's Campaigns",
  "Mongol Invasions",
  "Crusades & Holy Wars",
  "War of 1812",
  "Spanish-American War",
  "Boer Wars",
  "Russian Revolution & Civil War",
  "Chinese Civil War",
  "Indo-Pakistani Wars",
  "Six-Day War",
  "Yom Kippur War",
  "Falklands War",
] as const;

/**
 * Get a random category from the 525 available categories
 */
export function getRandomCategory(): string {
  const randomIndex = Math.floor(Math.random() * TRIVIA_CATEGORIES.length);
  return TRIVIA_CATEGORIES[randomIndex];
}

/**
 * Get a specific category by number (1-525)
 */
export function getCategoryByNumber(num: number): string {
  if (num < 1 || num > TRIVIA_CATEGORIES.length) {
    throw new Error(`Category number must be between 1 and ${TRIVIA_CATEGORIES.length}, got ${num}`);
  }
  return TRIVIA_CATEGORIES[num - 1]; // Convert to 0-indexed
}

/**
 * Get total number of categories
 */
export function getTotalCategories(): number {
  return TRIVIA_CATEGORIES.length;
}
